// Runs automatically before `npm run build` (npm's `prebuild` lifecycle hook).
// Vercel injects Project Settings > Environment Variables into `process.env` at build
// time, so setting API_URL there (per environment: Production / Preview) controls which
// backend the production bundle points at without touching source.
const fs = require('fs');
const path = require('path');

const DEFAULT_API_URL = 'https://localhost';
const apiUrl = process.env.API_URL || DEFAULT_API_URL;

const outPath = path.join(__dirname, '..', 'src', 'environments', 'environment.prod.ts');
const content = `// Auto-generated by scripts/set-env.js from the API_URL env var — do not edit directly.
export const environment = {
  production: true,
  apiUrl: '${apiUrl}'
};
`;

fs.writeFileSync(outPath, content);
